# More Functions

## Trigonometric Functions 

**Notation** Consider an angle $\theta$ in standard position. Let $P$ be the point of intersection of the terminal side and the unit circle. We define sine and cosine functions from $\mathbb{R}$ to $\mathbb{R}$:

- $\sin\theta=y-$coordinate of $P$

- $\cos\theta=x-$coordinate of $P$

**More trigonometric functions** The tangent, cotangent, secant and cosecant functions are defined as follows:

- $\tan x=\frac{\sin x}{\cos x}$

- $\cot x=\frac{\cos x}{\sin x}$

- $\sec x= \frac{1}{\cos x}$

- $\csc x=\frac{1}{\sin x}$

where the domains are 

- $\text{dom}(\tan)=\text{dom}(\sec)=\mathbb{R}\backslash\{\pm\frac{\pi}{2},\pm\frac{3\pi}{2},\ldots\}$

- $\text{dom}(\cot)=\text{dom}(\csc)=\mathbb{R}\backslash\{\pm\pi,\pm2\pi,\ldots\}$

**Properties**

1. The sine and cosine functions are periodic with period $2\pi$

2. The tangent function is periodic with period $\pi$.

3. The sine and tangent functions are odd functions and the cosine function is an even function.

4. The graphs of the sine and tangent functions are symmetric about the origin and the graph of the cosine function is symmetric about the $y$-axis.

5. The graph of the cosine function can be otained from that of the since function by moving it $\frac{\pi}{2}$ units to the left.

**CAST Rule**

**Sine, Cosine and Tangent of some special angles**

**Important identities** 

- $\sin^2 x + \cos^2 x=1$

- $1+\tan^2x=\sec^2x$

- $\sin(x+\frac{\pi}{2})=\cos x$

- $\cos(\pi-x)=-\cos x $

**Compound angle formulas**

- $\sin(A+B)=\sin A\cos B + \cos A\sin B$

- $\cos(A+B)=\cos A\cos B-\sin A\sin B$

**Continuity of sine and cosine** Both of them are continuous on $\mathbb{R}$.

**Important limits**

- $\underset{x\rightarrow0}{\lim}\frac{\sin x}{x}=1$

- $\underset{h\rightarrow0}{\lim}\frac{\cos h-1}{h}=0$

**Differentiation of Trigonometric Functions**

**Derivative of sine** The sine function is differentiable on $\mathbb{R}$ and its derivative is the cosine function:
$$\frac{d}{dx}\sin x=\cos x$$

**Derivative of cosine** The cosine function is differentiable on $\mathbb{R}$ and its derivative is the negative of the sine function:
$$\frac{d}{dx}\cos x=-\sin x$$

**Derivative of tangent** The tangent function is differentiable on its domain and its derivative is the square of the secant function, that is,
$$\frac{d}{dx}\tan x=\sec^2 x,~~~x\neq\pm\frac{\pi}{2},\pm\frac{3\pi}{2},\ldots.$$

## Exponential functions 

**Euler number** $e=\underset{m\rightarrow\infty}{\lim}\left(1+\frac{1}{m}\right)^m$

**Exponential function** The function $f(x)=e^x=\exp(x)$ in which the base is the number $e=2.7183$.

**The derivative of the exponential function** If $f(x)=e^x$ then $f'(x)=e^x$. If $f(x)=c^x$ then $f'(x)=c^x\ln c$.

## Logarithmic functions 

**Natural logarithm** A logarithm to base $e$. IF $M=e^n$ then n is the natural logarithm of $M$, and we write $n=\ln M$.

**The derivative of the logarithm function** If $f(x)=\ln x$ then $f'(x)=\frac{1}{x}$. If $f(x)=\log_c x$ then $f'(x)=\frac{1}{x\ln c}$.



## Applications

### Compound interest 

**Simple interest** The interest which is paid directly to the investor instead of being added to the original amount.
$$S=P\times(1+rt)$$

**Compound interest** The interest which is added on to the initial investment, so that this will itself gain interest in subsequent time periods.
$$S=P\times(1+r)^t$$

**Continuous compounding** The limiting value when interest is compounded with ever-increasing frequency.
$$S=P\times e^{rt}$$

**Annual percentage rate** The equivalent annual interest paid for a loan, taking into account the compounding over a variety of time periods.

**Principal** The value of the original sum invested.

**Future value** The final value of an investment after one or more time periods.


